ARG BASE_JDK_IMAGE=eclipse-temurin:21-jdk-alpine
ARG BASE_JRE_IMAGE=eclipse-temurin:21-jre-alpine
#Stage 1: Dependencies
FROM ${BASE_JDK_IMAGE} AS dependencies
RUN apk add --no-cache maven
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline

#Stage 2: Build
FROM dependencies AS builder
COPY src ./src
RUN mvn package

#Stage 3: Runtime
FROM ${BASE_JDK_IMAGE} AS runtime
WORKDIR /app
VOLUME ["/app/logs"]
ARG JAR_FILE=*.jar
COPY --from=builder /build/target/${JAR_FILE} app.jar
ARG IMAGE_VERSION=1.0
LABEL org.opencontainers.image.authors="Doc" \
 org.opencontainers.image.version=${IMAGE_VERSION} \
 org.opencontainers.image.title="Users Microservice" \
 org.opencontainers.image.description="Spring boot service to manage users"
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]
#CMD ["--spring.profiles.active=test"]
